---
- name: Basic Server Setup
  hosts: local
  connection: local
  become: yes

  tasks:
    - name: Copy JAR file 
      copy:
        src: "target/MyFirstMavenApp-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/HelloMaven.jar"
